// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import RemovalsController from "controllers/removals_controller"
application.register("removals", RemovalsController)

import TurboFramesController from "controllers/turbo_frames_controller"
application.register("turbo-frames", TurboFramesController)

import TurnstileController from "controllers/turnstile_controller"
application.register("turnstile", TurnstileController)

export function registerControllers(application) {
  application.register("turnstile", TurnstileController)
}
